name: nlp_masterthesis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - streamlit
  - scikit-learn
  - pandas
  - psutil
  - tk
  - decorator
  - setuptools
  - ca-certificates
  - wcwidth
  - wheel
  - ipython
  - traitlets
  - openssl
  - pygments
  - pyzmq
  - prompt-toolkit
  - nest-asyncio
  - libzlib
  - parso
  - libsodium
  - asttokens
  - pywin32
  - xz
  - executing
  - bzip2
  - pickleshare
  - jedi
  - matplotlib-inline
  - entrypoints
  - libsqlite
  - tzdata
  - python=3.10
  - backcall
  - zeromq
  - six
  - debugpy
  - jupyter_client
  - backports.functools_lru_cache
  - stack_data
  - python-dateutil
  - python_abi
  - pyparsing
  - pip
  - pure_eval
  - packaging
  - libffi
  - tornado
  - colorama
  - jupyter_core
  - backports
  - ipykernel
  - pre_commit
  - mypy
  - black
  - flake8
  - isort
  - interrogate
  - xenon
  - pylint
  - bandit
  - pytest
  - nltk
