name: nlp_masterthesis
channels:
  - defaults
dependencies:
  - pytest
  - flake8
  - parso
  - asttokens
  - tk
  - tzdata
  - jedi
  - backports
  - numpy
  - pyzmq
  - interrogate
  - six
  - wcwidth
  - python-dateutil
  - setuptools
  - scikit-learn
  - pygments
  - jupyter_client
  - libzlib
  - pickleshare
  - pylint
  - pure_eval
  - pyparsing
  - debugpy
  - entrypoints
  - ipython
  - bandit
  - isort
  - nest-asyncio
  - bzip2
  - ipykernel
  - pre_commit
  - colorama
  - zeromq
  - tornado
  - traitlets
  - psutil
  - libffi
  - matplotlib-inline
  - stack_data
  - pip
  - openssl
  - decorator
  - mypy
  - wheel
  - streamlit
  - xenon
  - backports.functools_lru_cache
  - black
  - pywin32
  - xz
  - pandas
  - prompt-toolkit
  - executing
  - python=3.10
  - libsodium
  - jupyter_core
  - libsqlite
  - python_abi
  - packaging
  - ca-certificates
  - backcall
  - beautifulsoup4
  - click
  - lxml
